### PR TITLE
mode/app: decouple mode creation from gui components

### PR DESCRIPTION
**Pull request by sophiekovalevsky**
This implementation feature tries to separate `Modes` logic behavior / actions from gui elements that should be exposed on gui and that need somehow access to those behavior / actions. 

**Mode Handler:** 

The main tasks of this class are:

- Send and receive signals from GUI widgets that act upon the different modes.
- Manage existing modes and operation upon them: creation, select of active mode
- Provide what current modes exists
- Propagate settings to corresponding mode

**Mode Window:**

Relevant features:

- Creation and configuration of widgets that interacts with Mode Handler
- Send and receive signals from Mode Handler that acts upon the different widgets

Improvements regarding current state: 
- QTabWidget is used to abstract the handling of accessing different QTabBars.

### CODE REVIEW

**Comment by jankae** [comment]
I haven't looked at it in detail, but there seem to be some issues with it:
1. Mode tab is not in the corner widget anymore. I assume this is on purpose, but it uses up a bit more space now that otherwise would have been available for the graphs:
image
I think I would prefer to keep it at the top right corner. Or if moving it, move the "add mode"-button with it.
2. Some weird graphics issue on the main menu, the entries now have thin lines under them (on Ubuntu):
image
I have seen that before, if I remember correctly, it had something to do with the height of the corner widget
3. Movable tabs for the modes are nice, but there is a problem with it: if I change the order of the tabs, I get the wrong toolbars (probably setting toolbars based on the index of the active tab?).
 Default order, VNA selected, correct toolbar:
image
Changed order, still VNA selected but suddenly I get the SA toolbar:
image

**Comment by sophiekovalevsky** [comment]
> 1. Mode tab is not in the corner widget anymore. I assume this is on purpose, but it uses up a bit more space now that otherwise would have been available for the graphs:
>    image
>    I think I would prefer to keep it at the top right corner. Or if moving it, move the "add mode"-button with it.

Initially, the first option I tried qas to layout it as it was originally but then I found that wouldn´t be possible to use `QTabWidget` anymore. 

Another option that I tried was as you suggested to set the "add mode"-button on the corner widget of the actual QTabWidget, but there is the case when there is actual mode created and then, the corner widget disappears. Hence, that's the why of having it in that way.

In conclusion, I will change code so that will be as it was before.

> 2. Some weird graphics issue on the main menu, the entries now have thin lines under them (on Ubuntu):
>    image
>    I have seen that before, if I remember correctly, it had something to do with the height of the corner widget

I did this on purpose because otherwise "add mode"-button looked slightly different and didn´t think that it was a big issue afterall. Falling back to original design I'll guess this will be fixed. 

> 3. Movable tabs for the modes are nice, but there is a problem with it: if I change the order of the tabs, I get the wrong toolbars (probably setting toolbars based on the index of the active tab?).
>    Default order, VNA selected, correct toolbar:
>    image
>    Changed order, still VNA selected but suddenly I get the SA toolbar:
>    image
That's true and I guess I didn´t pay too much attention to it until you brought that up. I will try to fix it.

**Comment by sophiekovalevsky** [comment]
I made changes as per suggested. Hopefully my test iterations allowed me to think that reviewing process can keep moving forward.

After analyzing a bit in detail the feature about moving tabs I come with the conclusion that feature it's not really required at this point. Since it will add extra code that I would rather prefer  you may review it after reviewing this one in particular. Then, I will leave that out.

**Comment by sophiekovalevsky** [comment]
I just discovered another bug in the implementation, I'll let you know when is ready.

**Comment by sophiekovalevsky** [comment]
Feature is ready to test. 

I had to force and rebase this branch because it was way simpler for you to review. I tried to maintain as close as possible past commits but with all these new changes I need it to make some adjustments anyways.

**Comment by jankae** [comment]
Seems to work, thank you for all the work. One minor point: with your previous PR (#126), I could move tabs without this triggering a device configuration. Now, the device settings are updated whenever the tab of the active mode is moved. This causes a restart of the current sweep, which is not necessary. It doesn't really matter (I don't expect a lot of people to move tabs while sweeping) but I quite liked the behavior we had before.

I have a few small question about the code, I'll add review comments for that.

**Comment by sophiekovalevsky** [comment]
Thanks for the tiny observation. It's fixed now.

**Comment by jankae** [comment]
Thank you for integrating that.
I played around with it a little bit more and found another thing: Changing the mode via SCPI does not change the active tab in the ModeWindow. Example:
1. Start GUI
2. Connect to it via telnet
3. Issue command: :DEV:MODE SA
4. GUI switches to SA mode (toolbars, graphs and docks are all correct) but the VNA tab is still selected.

There is now some mixed responsibility for switching modes. This is mainly handled by ModeHandler, but you can still call Mode::activate directly, which skips the ModeHandler completely (this is whats happening with the SCPI command).

I think some further work on separating functionality is required. As it is now, the Mode class is still this weird standalone-ish class with functions as
```c
static Mode *getActiveMode();
static Mode *createNew(AppWindow *window, QString name, Type t);
```
which are probably more suited for the ModeHandler. Ideally, the Mode class is completely oblivious that other modes may exist as well and has no public functions for changing the mode.

I agree that this is not especially easy and probably even more difficult if you have to understand unfamiliar code. But as this PR is now, I don't feel comfortable merging it, sorry. It seems to me as if it splits the same functionality across three different classes with no clear boundaries and responsibilities (to be fair, ModeWindow is fairly contained. I mostly have a problem with Mode and ModeHandler).

But I am all for decoupling these functions in different classes. If you are willing to further work on this, I am absolutely for merging this in the future :)

**Comment by sophiekovalevsky** [comment]
Thanks for all your observations. 

> which are probably more suited for the ModeHandler. Ideally, the Mode class is completely oblivious that other modes may exist as well and has no public functions for changing the mode.

Would you please elaborate last statement concerning changing the modes. 

I'll put this PR in draft until I fix the issues you were mentioning.

**Comment by jankae** [comment]
> Would you please elaborate last statement concerning changing the modes.

Sure. It looks to me like you want to split the functionality I packed into the Mode class into different modules (which I think is a good idea). Maybe I am wrong, but I interpreted your plan like this:
- Mode gets almost reduced to an interface, abstracting the VNA, SG and SA classes
- ModeHandler takes care of creating/deleting/switching between modes
- ModeWindow is the GUI part (from which I inferred, that Mode and ModeHandler should not do any GUI stuff anymore).

So far so good, seems like a logical split to me. But as the PR is now, the lines get somewhat blurry between Mode and ModeHandler:
- Mode still contains some GUI stuff (setting the correct plots, toolbars and docks). Maybe this gets too messy when moving it to somewhere else, I am not completely against keeping it here
- Mode contains the activate/deactivate functions. I think they are needed but should explicitly be for use by ModeHandler, otherwise ModeHandler loses track of the active mode. Maybe make them private/protected and use friend class ModeHandler? Not the cleanest solution but I can't think of anything better right now
- Mode still has static functions which I think really belong to ModeHandler. Some static functions (for enum string conversions) can obviously stay there, but e.g. the createNew function fits way better in ModeHandler.

What I think would be a good approach:
- Mode class still handles activation/deactivation of modes but one instance does not effect other instances anymore. Example: right now, activating a mode first disables the currently active mode. This obviously needs to happen but I think ModeHandler should take care of it. The Mode class instance shouldn't really need to know which is the currently active mode.
- ModeHandler creates new modes, deletes modes and also handles the transition from one mode to the other (by deactivating the old mode followed by activating the new mode). It also keeps track of the new mode

From another perspective:
- Whenever I want to create/delete or change the active mode, I'll call some function of ModeHandler
- Whenever I want to change settings of a mode (e.g. setting the averaging style), I'll call some function of Mode
- It shouldn't be possible to switch modes without going through ModeHandler. Being able to call Mode::activate() directly just invites future bugs.

I hope this cleared things up a bit. Maybe I am also misunderstanding your intentions for this PR, feel free to correct me.

**Comment by sophiekovalevsky** [comment]
You're right about your assumptions about what this pull request is about. 

> Mode still contains some GUI stuff (setting the correct plots, toolbars and docks). Maybe this gets too messy when moving it to somewhere else, I am not completely against keeping it here

I guess this can be incorporated in the future into a GUI section but not really sure until I get more familiarize with all widgets concerning to every mode. I'll kept it there, but I would like to think that we can completely separate behavior logic from gui actions. 

> Mode contains the activate/deactivate functions. I think they are needed but should explicitly be for use by ModeHandler, otherwise ModeHandler loses track of the active mode. Maybe make them private/protected and use friend class ModeHandler? Not the cleanest solution but I can't think of anything better right now

It make sense to me and actually it's achievable to implement. Thanks for the hint. What I'm curious about would be in which circunstances this approach can lead to think it's not a cleanest solution?  

> Mode contains the activate/deactivate functions. I think they are needed but should explicitly be for use by ModeHandler, otherwise ModeHandler loses track of the active mode. Maybe make them private/protected and use friend class ModeHandler? Not the cleanest solution but I can't think of anything better right now

Agreed. 

> Whenever I want to change settings of a mode (e.g. setting the averaging style), I'll call some function of Mode

 When doing the pull request I wasn´t 100% sure if moving `setAveragingMode()`  was the right thing to do because it's a setting that only cares when dealing with either `VNA` or `Spectrum Analyzer` classes rather than a generalize action to encapsulate on `ModeHandler`. Is this what you were referring to? 

On the other hand, checking this line: 

https://github.com/jankae/LibreVNA/blob/master/Software/PC_Application/Calibration/amplitudecaldialog.cpp#L27

What are you thoughts in terms of setting `getActiveMode()` as static rather than a instance method? My thinking would be to set it as an instance method but it can be the other way around, it just depends the use of two different mode handlers can be used which I think not. Assuming that its implemented as a instance method, would be reasonable to pass the pointer directly instead of using a method in `AppWindow` to retrieve it? i.e. 

`ReceiverCalDialog::ReceiverCalDialog(Device *dev, ModeHandler *handler)` or `appwindow->getModeHandler()`

Furthermore, within childs `Mode`, there are some places where it's required to know what active mode is currently selected and I'm not sure what would be the optimal approach on this since in either or other case these modes needs to have some type of awareness of mode handler. For that, my proposal would be to use the following: 

`window->getModeHandler()->getActiveMode()` 

This statement can go e.g. here: 

https://github.com/jankae/LibreVNA/blob/master/Software/PC_Application/VNA/vna.cpp#L804

**Comment by sophiekovalevsky** [comment]
> Approach 2 looks like the overall cleaner solution to me, although it requires a bit more code. But it would simplify ModeHandler and get rid of the casts there.

Can we preserve the logic that updates all pertinent modes when preferences are updated rather than update them when swaping to next active mode?  I've made the changes so that we can delete the cast when calling `setAveragingMode()`. If you still believe that it's not cleaner, I will change it. 

> The only exception is in Mode::activate() to deactivate the currently active mode.

Sorry I didn't get this. Shouldn't be enough to change state for `isActive` whenever `Mode::activate()`  and `Mode::deactivate()` are called?

I'll guess probably this PR is ready for review.

**Comment by jankae** [comment]
> Can we preserve the logic that updates all pertinent modes when preferences are updated rather than update them when swaping to next active mode?

Yes, looks good, lets keep it that way.

> Sorry I didn't get this. Shouldn't be enough to change state for `isActive` whenever `Mode::activate()` and `Mode::deactivate()` are called?

Yes, that is enough for the implementation in `Mode`. What I meant is that the desctivation of the previously active mode should be moved to `ModeHandler`, which you did.

> I'll guess probably this PR is ready for review.

I found one last small issue: after closing the amplitude calibration dialog, the previously active mode is not restored. But since I need to merge this PR manually anyway, I'll just quickly fix that as well.

Thank you for all the work, separation of functionality is now much better than it was previously :)

**Comment by sophiekovalevsky** [comment]
@jankae thanks to you for reviewing it.

**Pull request merged**
