### PR TITLE
Qt6 gui

### PR DESCRIPTION
**Pull request by crvux**
Updated #200 PR

### CODE REVIEW

**Comment by jankae** [comment]
Hi, thanks for updating the PR. At the moment I still have some issues with the toolchain (both on my own machine and the automatic toolchain on Github). If I can get these solved, I will merge this.

**Comment by jankae** [comment]
Looks like I managed to fix the toolchain, although I am wondering how you were able to compile this pull requests. I'll run some more checks tomorrow. The only thing I am worrying about is the macOS workflow on Github. I am unable to test the result of that and can just hope that the compiled binary still works.

**Comment by crvux** [comment]
I compile this using qmake version 6.4.2 on a Fedora distribution
Just run
`cd Software/PC_Application/LibreVNA-GUI/ && qmake && make -j$(nproc)`

**Comment by lucasub** [comment]
> I compile this using qmake version 6.4.2 on a Fedora distribution Just run `cd Software/PC_Application/LibreVNA-GUI/ && qmake && make -j$(nproc)`

Hi, I clone the latest repository (15 December 2023) but when I try to compile with the command qmake && make -j$(nproc)   returned this error:

./savable.h: In static member function ‘static nlohmann::json_abi_v3_11_2::json Savable::createJSON(std::vector<SettingDescription>)’:
./savable.h:83:24: error: ‘class QVariant’ has no member named ‘metaType’; did you mean ‘nameToType’?
   83 |             switch(val.metaType().id()) {
      |                        ^~~~~~~~
      |                        nameToType
make: *** [Makefile:17980: caldevice.o] Errore 1
make: *** Attesa per i processi non terminati....
make: *** [Makefile:18172: librecaldialog.o] Errore 1
make: *** [Makefile:18912: calibrationmeasurement.o] Errore 1
make: *** [Makefile:18738: calibration.o] Errore 1

if you can write in more detail how to compile the source both from the command line and from QTCreator. For this I thank you very much for the time you are dedicatin

I need to compile it because I downalod version GUI 1.5.0 for Ubuntu but when I try to calibrate the VNA, application creash with this errror:

Istantanea_2023-12-15_09-04-06

Istantanea_2023-12-15_09-05-07

Thank you, see you soon
Luca

**Comment by jankae** [comment]
> ./savable.h:83:24: error: ‘class QVariant’ has no member named ‘metaType’; did you mean ‘nameToType’?

This very much sounds like you are compiling with Qt5.

Qt6 has 'metaType' but no 'nameToType': https://doc.qt.io/qt-6/qvariant.html#metaType
Qt5 has 'nameToType' but no 'metaType': https://doc.qt.io/qt-5/qvariant.html#metaType

> I need to compile it because I downalod version GUI 1.5.0 for Ubuntu but when I try to calibrate the VNA, application creash with this errror:

Can you please open an issue for that problem and describe in detail the steps you are executing up until the crash. The error message from your screenshot is unrelated and doesn't help me here.

**Pull request merged**
