### PR TITLE
app: add LibreVNA logo and use it as icon launcher

### PR DESCRIPTION
**Pull request by sophiekovalevsky**
@jankae my only concern about this implementation is what to expect in Mac OS, I won't be able to test it. 

I've added a banner to the project to be seen in [README](https://github.com/sophiekovalevsky/LibreVNA/tree/icon-app), this is okey on your side? If so, I will move PR from draft to ready since need it to change the banner logo to point out upstream. Also, I created a desktop file so that Linux / GNU can be able to index the app if they want.

Launcher desktop:

image

As favorite app: 

image

### CODE REVIEW

**Comment by jankae** [comment]
Thanks, logo on the README looks great :) I'll merge this once you changed the logo link

**Comment by sophiekovalevsky** [comment]
@jankae logo link has been changed and PR is ready.

**Comment by jankae** [comment]
Could you also provide an .svg file (or other vector format) of the logo please? Might be useful if a different size is required at some point

**Comment by sophiekovalevsky** [comment]
Done through https://github.com/jankae/LibreVNA/pull/70

I guess at this point, there is no issue to set svg into resources folder.

**Pull request merged**
