### PR TITLE
implement sweep standby operation

### PR DESCRIPTION
**Pull request by andredunford**
This PR addresses the intended aim of PR #180, and implements standby operation for low latency single sweep acquisitions.

A new packet `PacketType::InitiateSweep` is introduced to the USB Protocol, with an accompanying function `VNA::InitiateSweep()`, which conditionally wraps `FPGA::StartSweep()`.

The configuration field of `SweepSettings` is updated with a bit for indicating standby operation. In standby operation, the VNA will not automatically start a sweep when configured. Instead, it will wait indefinitely for `InitiateSweep` packets to trigger data collections. 

When standby operation is activated, it becomes the host's responsibility to put the device into idle mode with a `SetIdle` packet. However, default timeout behaviour is maintained if a sweep is halted unexpectedly.

In default configuration (i.e. standby bit = 0), an `InitiateSweep` packet will elicit a Nack response.

### CODE REVIEW

**Comment by jankae** [comment]
Hi Andre,

I like this solution a lot more, thank you :)

Just one minor thing:

> ... and timeout to idle mode 1000ms after sweep is completed ...

There is no timeout when the sweep is finished. The LibreVNA will restart the sweep from the beginning by itself. This continues until a SetIdle packet is received. The timeout only occurs if something goes wrong on the hardware side (e.g. PLLs not locking).

I haven't tested this on actual hardware but I believe you unintentionally disable this timeout for the complete sweep when the standby flag is set. The timeout should still work during the sweep (just not before the sweep when waiting for the InitiateSweep packet).

An easy way to trigger the timeout on the hardware is to use an external reference and disconnect it during the sweep, this will prevent the PLLs from locking.

**Comment by andredunford** [comment]
Thanks Jan!

I left the timeout in `VNA::SweepHalted()` unchanged, so it will still respect the halted sweep timeout.  

However, I noticed that when in standby for longer than 1s (1000000us) the main loop in `App_process()` invokes `HW::SetMode()` to go to idle mode, then resubmits the previously received packet, and continues to do this every timeout period (1s) until eventually set to idle mode manually.   

https://github.com/jankae/LibreVNA/blob/5ad44c780ca5fac78128ce13c4375418cced406b/Software/VNA_embedded/Application/App.cpp#L317-L324

This timeout period is set in `HW::TimedOut()`, which appears to check the time since the last ISR (presumably from the last completed measurement).

https://github.com/jankae/LibreVNA/blob/5ad44c780ca5fac78128ce13c4375418cced406b/Software/VNA_embedded/Application/Hardware.cpp#L301-L317

Conditionally bypassing this timeout allows the device to wait indefinitely for all future `InitiateSweep` packets until a `SetIdle` packet is sent intentionally, without cycling in and out of idle mode repeatedly.

I noticed that you have a similar conditional statement on line 306 of `HW::TimeOut()` which also checks if the device is in generator mode.  The use cases seem to be parallel.  Would you prefer that I add the standby condition here instead?   Functionally, I don't believe there is a difference, but perhaps this fits more cleanly with your current implementation?

**Comment by andredunford** [comment]
I went ahead and relocated the standby condition to `HW::TimedOut()`, as it does seem to be more cohesive there.  But please let me know if you'd like this addressed differently.

**Comment by andredunford** [comment]
I have a solution that now handles your stated case. I have tested it by using an external reference and disconnecting it during sweeps.

The value of `AUX3` is now evaluated along with the standby flag to provide an `IsWaitingInStandby()` function. 

The implementation will:
- initially wait in a configured standby state without toggling to idle
- return to idle if a halted sweep is prolonged past timeout (100ms)
- toggle to idle and resubmit previous packet if hardware timeout (1s) is reached while a sweep is active (unlocked PLLs, etc.)

However, there is one remaining issue:  the device will still toggle to idle and resubmit the previous packet one time after a successful sweep if the timeout is reached before the next `InitiateSweep` packet is received. After toggling once, it then waits until the next `InitiateSweep` is received. 

Although better than continuous toggling, this is not ideal behaviour. It can result in longer latency and jitter for intermittent sweeps which are initiated near the timeout period.

I believe this is occurring because `AUX3` is not being brought low again after the first successful sweep.  Since we're not expecting an `FGPA::AbortSweep()` until going to idle intentionally, is there somewhere else it would be appropriate to set `AUX3` low again while waiting for the next `FPGA::StartSweep()`?

Alternatively, is there another existing indicator of hardware activity that you think would work better for this purpose?  It should indicate only when the hardware is expected to be responsive (e.i. a case for `HW::TimedOut()` to evaluate a timeout).

**Comment by andredunford** [comment]
Thanks for your time reviewing this, Jan.

I do see your point about `AUX3`. I believe I have a suitable alternative, per your suggestion:

A boolean flag `waitingInStandby` is introduced in `VNA.cpp` and initialized to false.  
- It is set to true either in `VNA::Setup()` when standby mode is established, or in `VNA::Work()` when a sweep is completed.
- It is set to false either when `InitiateSweep()` is called (sweep is active and needs to be monitored for timeout), or when `HW::SetIdle()` is called and the standby state is ended. 

This appears to provide the desired behaviour in all test scenarios.

The previous commit using `AUX3` is reverted.

P.S. I'm not sure why the firmware build fails here.  I've tested several times locally with clean build, and have no undefined reference issues.

**Comment by jankae** [comment]
Thanks a lot Andre, looks good to me now :)

**Comment by andredunford** [comment]
Awesome, thanks for your feedback leading to the right solution!

**Pull request merged**
