### PR TITLE
app: refactor tasks creation

### PR DESCRIPTION
**Pull request by sophiekovalevsky**
@jankae here my attempt in trying to improve a little the way tasks are created, I would like to know your input on this. 

- Can we select whether if we can create tasks either by cmsis or by freertos apis? There is an special reason behind why Led task is created using freertos that I'm missing? mabe `vTask{Resume,Suspend}` not properly working with cmsis? 
-  Before actually starting kernel, probably a check whether the task were successfully would be relevant? kernel needs at least one task created before his execution. The same condition is added on LedStatus task.
- In long-term future, libreVNA firmware will be handled by IDE software from ST? In terms of adding new feature if that it's required? This is to bear in mind that I need take care in which places should I add code. 
- App logic has been split in a way we can clearly identify what needs should be executed when starting and when task runs indefinitely. `osDelay` was not executing before, this was intentional?

What do you think about it?

### CODE REVIEW

**Comment by jankae** [comment]
> Can we select whether if we can create tasks either by cmsis or by freertos apis? There is an special reason behind why Led task is created using freertos that I'm missing? mabe vTask{Resume,Suspend} not properly working with cmsis?

I am used to the freertos API (had experience with freertos before using CubeMX/CubeIDE), that is why I only use them in my own code.

> Before actually starting kernel, probably a check whether the task were successfully would be relevant? kernel needs at least one task created before his execution. The same condition is added on LedStatus task.

I am using static task creation (by supplying the required RAM directly instead of relying on heap allocation). According to the [API](https://www.freertos.org/xTaskCreateStatic.html) this always succeeds, as long as you don't supply nullpointers for the task memory.

> In long-term future, libreVNA firmware will be handled by IDE software from ST? In terms of adding new feature if that it's required? This is to bear in mind that I need take care in which places should I add code.

As many people, I have a love-hate-relationship with the STM HAL (which is generated by the CubeMX/CubeIDE). It significantly simplifies initialization of the hardware but causes some code bloat and imposes other restrictions. One of these restrictions is that you are only allowed to add your own code in the user code sections (indicated with USER CODE BEGIN/USER CODE END). If you add stuff anywhere else, it will be removed when the code is generated the next time. That is why I usually jump out of the generated code as soon as possible. I do this by putting all of my own code in the "Application" folder. The only lines I add to the generated code are the include to my app.h and the call to App_Start (which does not return).
I am then free to edit the code in the application folder as I like, without having it accidentally changed by the code generation.

This is not always possible, sometimes you need a more specific behavior in the startup code or it may even contain bugs. My workaround for these instances is to add patchfiles to the project that are executed by the makefile before the compilation, whenever the code has been regenerated. Thankfully, this wasn't necessary with this project.

> App logic has been split in a way we can clearly identify what needs should be executed when starting and when task runs indefinitely. osDelay was not executing before, this was intentional?

I like the split into setup/loop functions but would prefer to handle all this in app.cpp/.h (as little dependency from main.c, as stated above). The osDelay is not required in the loop, xTaskNotifyWait already yields to other tasks and waits until an event is available.

**Comment by sophiekovalevsky** [comment]
@jankae I will have to make a couple of test during today and I'll let you know when my changes are ready for you to check. Thanks.

**Comment by sophiekovalevsky** [comment]
@jankae, now it make more sense to me several implementations within the project. Thanks for the hints. 

Based on your comments I revert modifications code automatic code generated by CubeMX as you suggested and also on task verification.

**Comment by jankae** [comment]
Hi, thanks for adapting the pull request and keeping it compatible with future CubeMX code generation. One tiny detail I noticed: you renamed the LED_TASK_STACK to LED_STATUS_TASK_STACK_SIZE_BYTES. With FreeRTOS, the stacksize is given in words (32bit in this case, StackType_t is defined as uint32_t). If you could please change that (just to avoid confusion in the future), I'll merge it

**Comment by sophiekovalevsky** [comment]
@jankae changed.

**Comment by jankae** [comment]
Thank you :)

**Comment by sophiekovalevsky** [comment]
@jankae thanks so much too you for all you assistance :D

**Pull request merged**
