### PR TITLE
widgets/charts: implement polar diagram

### PR DESCRIPTION
**Pull request by sophiekovalevsky**
The following implementation represent `Sii` parameters in a polar chart.

I would like to receive your initial feedback on this. During development I came up with the following thoughts: 

- It's desirable to apply this chart to parameters not equal to `Sii`?
- It seems that some behavior of `TraceSmithChart` can be shared with `TracePolarChart` but I wasn't sure to actually make a base class right away without having your opinion first. The main drawback that I see in inherit Smith and Polar charts from this base class is adding a extra layer of parent class. Having a third layer in this case would be maintainable in the future?

- There is a new funcionality in this chart that can be used on `SmithChart` as well and it's moving horizontal axis. The expected behavior follows:
  - When horizontal axis is moved some distance, the phasor representation is always constrained by the `edgeReflection` circle.
  - Trace points when are out of visible area may have some empty spaces near `edgeReflection` circle because there is no interpolation between the sample point and the next one. This can be exacerbated if zoom factor is higher.
image

### CODE REVIEW

**Comment by jankae** [comment]
Wow, thank you so much for this addition. I haven't looked at it in detail yet but my initial thought is to go with a common base class for smith and polar charts as there are only a couple difference between them (mainly the grid lines and pixel<->coordinate conversions.

**Comment by sophiekovalevsky** [comment]
@jankae ready for review. 

- Smith Chart class inherits from Polar class
- Offset in real axis on Smith Chart have been added

**Comment by jankae** [comment]
Thank you very much :) I am unavailable for a few days and will review/merge this in about a week.

**Comment by jankae** [comment]
Merged, and thanks again for this significant contribution :)

I made slight changes:

> It's desirable to apply this chart to parameters not equal to Sii?

I think so and am allowing Sij traces to be added to polar charts now

> Trace points when are out of visible area may have some empty spaces near edgeReflection circle because there is no interpolation between the sample point and the next one. This can be exacerbated if zoom factor is higher.

Improved handling of line drawing in smith and polar charts. The line is now drawn all the way to the circle in case one point is outside of it.

**Comment by sophiekovalevsky** [comment]
@jankae you're welcome. 

> Improved handling of line drawing in smith and polar charts. The line is now drawn all the way to the circle in case one point is outside of it.

I haven't look thoroughly the changes but while making some tests, I discovered the following: 

image

Is this an expected result?

**Comment by jankae** [comment]
Hm, looks like I forgot to check this "improvement" when an x-axis offset is used... Will soon be fixed

**Comment by jankae** [comment]
Should be fixed now, I forgot to handle a special case in `constrainLineToCircle`

**Comment by sophiekovalevsky** [comment]
@jankae it works sooo great. Thanks.

**Pull request merged**
