### PR TITLE
replace USB protocol literals with named constants

### PR DESCRIPTION
**Pull request by andredunford**
Issue:
The USB communication protocol uses literals for data structuring and indexing, making the code challenging to understand and maintain. An update to packet structure would require manually locating and interpreting individual literal values with prior knowledge of their significance.

Fix:
This commit introduces a separate header file and namespace, `PacketConstants`, containing named constants to replace field-specific literals. It also standardizes buffer incrementation in `encode()`/`decode()` methods, and reduces some ambiguity with combined packet header length vs distinct header field length.

Constants were created in a separate header file so that they might easily be included in host projects which require the packet structure, without the device protocol declarations/implementations. 

Firmware has been built with CubeMX 1.8.0 and tested on device.

### CODE REVIEW

**Comment by andredunford** [comment]
My apologies... this clearly breaks the PC Application. I missed this, as I had built the GUI previous to the firmware changes. I will close this request, and review changes necessary in the application to fix.  On first glance, there is a missing reference now to `FirmwareChunkSize`, but I assume there may be more.

**Comment by jankae** [comment]
You probably just need to add the new PacketConstants file to the Qt project (in LibreVNA-GUI.pro). I'll get around to testing (and most likely merging) this PR later today

**Comment by andredunford** [comment]
Excellent, thank you!  It's very late here, so I'll take a look in the morning if you haven't had an opportunity by then.

**Comment by andredunford** [comment]
I've addressed the PC application build errors by including `PacketConstants.h` and updated the bad reference to `Protocol::FirmwareChunkSize` (now `PacketConstants::FW_CHUNK_SIZE`).

**Comment by jankae** [comment]
Thanks, works great :)

**Pull request merged**
