### PR TITLE
Automatic idle selection

### PR DESCRIPTION
**Pull request by andredunford**
To take advantage of faster acquisition times over indefinite intervals while the VNA is halted, a boolean flag and two USB protocol packet types are implemented.  

`HW::autoIdleFlag`: indicates whether the device should be set to idle mode after the fixed timeout period of 100ms. A getter and setter are provided. The default value is `true`.

`Protocol::PacketType::StopAutoIdle`: sets the `autoIdleFlag` to false, and prevents switching into idle mode after the timeout period. 

`Protocol::PacketType::StartAutoIdle`: sets the autoIdleFlag to true, and restores default timeout behaviour.

If automatic idling is halted, it becomes the host application's responsibility to put the device into idle mode, by sending either a `SetIdle` or `StartAutoIdle` packet.

The changes do not alter default behaviour, and only come into play when explicitly invoked.

### CODE REVIEW

**Comment by jankae** [comment]
I think I know what you want to achieve with this change (please correct me if I am wrong):
Reduce latency when starting a sweep with predetermined sweep settings. The general idea being that you configure the sweep, stop reading data which eventually leads to a halted sweep and then start reading data once you want to start the sweep.

I like the idea but I don't think this is the right approach. Here are the problems I am having with the solution:
- You are building on top of a feature that returns the device to idle mode when the host application fails to read the sweep data. This is just a fail safe to switch the sweep off if the communication fails for any reason. It shouldn't be used intentionally
- Depending on the IF bandwidth, it might take a long time until this fail safe is triggered (several seconds for low IF bandwidths, because the USB buffer only fills slowly)
- Once you start reading data again, you will start getting data from an arbitrary point in the sweep (wherever it was halted before)

Here are two implementation ideas I would prefer:
1. Leave the firmware unchanged and read sweep data continuously in the host application. You can just keep what you need and throw the rest of the data away. However, when you then decide at some point in time "now I need the data", you are still at a random point in the sweep
2. Optionally decouple the configuration of the sweep from the execution:
    - Add an additional "configure only" flag to the SweepSettings packet. If it is set, the sweep will be set up (PLL frequencies calculated,...) but not actually started
    - Add a new packet type "StartSweep". The previously configured sweep will only start once this packet is received
    - This will give you optimal latency without throwing away unnecessary data and you will also start the sweep from the beginning precisely when you need it

**Comment by andredunford** [comment]
Hi Jan, thanks for the detailed feedback.

You are correct about the intended use, and I agree with your assessment; my implementation piggy-backs on a feature with a different purpose. I can see how it would be sub-optimal for lower IFBWs, and requires hunting/dumping datapoints to get to the beginning of a sweep.

I think your implementation suggestion #⁠2 would be the most efficient solution, and would target the intended behaviour most directly. 

Currently, there is one remaining `unused` bit (LSB) in the configuration bitmask of the `SweepSettings` packet struct:

image

If this LSB is not reserved for another purpose, perhaps it could it be used as the flag to either:

- [0]: configure and begin the sweep immediately, maintaining current default behaviour
- [1]: configure only and wait for a `StartSweep` packet to initiate sweep

This seems clean and deliberate, while preserving the structure of the v12 protocol. 

If you think that would be appropriate, I’ll dig into the code a bit further, and try to implement this in the least invasive manner.

**Comment by jankae** [comment]
Sure, go ahead. That bit isn't reserved for anything at the moment.

**Comment by andredunford** [comment]
Closing this. The discussed implementation is now submitted in PR #182.

**Pull request closed without merging**
